### ISSUE TITLE
Import abritary CSV files

### ISSUE THREAD

**Issue by janopae** [NickvisionApps/Denaro#793]
Many programs allow importing data from arbitrary CSV or spreadsheet files (as long as they are organised in columns), allowing to select the correct column for a every type of data using dropdowns (including dropdowns for the most common date/time formats).

Banks are very creative at creating their own CSV formats, so I think such an interface would be a perfect fit for Denaro's domain.

Would this feature be in scope for Denaro?

**Comment by nlogozzo** [comment]
The purpose of Denaro's CSV import/export CSV feature is geared more towards backing up and restoring Denaro accounts, as it pretty much exports and imports all information to the file.

As you said yourself, banks can create some crazy CSV files. Plus, a lot of Denaro features aren't included in banks, which is why I don't plan on creating a UI for precise CSV import. 

Instead, we offer import from more standardized files (OFX and QIF) for import from banks, as those files have a precise layout.
